# Generated by Django 6.1 on 2026-08-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='contact_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='guest_id',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='identity_type',
        ),
        migrations.AddField(
            model_name='guest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='guest',
            name='id_proof',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
